# Generated by Django 5.2.7 on 2025-11-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0002_alter_blogpost_category_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
